### ISSUE TITLE
No Audio & Sierra crash on opening PDF Files.

### ISSUE THREAD

**Issue by SarthakOnGIT** [Twi1ight/Hackintosh-Clover-Config#1]
Hi,
I have tried to get Audio work by the way you mentioned. I download Lilu.kext & ApplaALC.kext & place them in Other directory of EFI partion(i.e /EFI/Clover/Kexts/Other). I tried Inject ID 1,2,3,11,13...
But nothing works.
Even sierra crashes to Login screen when opening PDF files by Preview.

So please help me to get rid of these.

Thanks.

**Comment by Twi1ight** [comment]
@SarthakOnGIT You may need to patch HDAS to HDEF in the ACPI section of your config.plist (ACPI -> DSDT -> Patches)
I found my solution here: [Audio](https://www.reddit.com/r/hackintosh/comments/4sil5p/audio_mechanic_old_patchfix_removal_applealc/?st=j3mwm9tp&sh=71d9d116)

**Comment by SarthakOnGIT** [comment]
Thanks.
I did it. I follow the guide you mention. Now it works flawlessly.
